BACKBONE:
  CONV1_T_SIZE: 7
  CONV1_T_STRIDE: 1
  MODEL_DEPTH: 18
  NAME: resnet3d_18
  NO_MAX_POOL: false
  N_CLASSES: 101
  N_INPUT_CHANNELS: 3
  PRETRAINED_MODEL: backbone/pretrain/r3d18_K_200ep.pth
  RESNET_SHORTCUT: B
  RESNET_WIDEN_FACTOR: 1.0
DATA:
  BATCH_SIZE: 24
  CLIP_LENGTH: 8
  CLIP_SIZE:
  - 8
  - 112
  - 112
  DATA_DIR: UCF-101-JPG
  EVAL_ONLY: false
  FRAME_SIZE: 112
  INCLUDE_TIMESLICES: true
  LABELS_DIR: label/UCF-101
  MEAN:
  - 0.4345
  - 0.4051
  - 0.3775
  NUM_SAMPLERS: 3
  RETURN_VIDEO_PATH: true
  SEED: 0
  SHUFFLE_LIST_SEED: 2
  STD:
  - 0.2768
  - 0.2713
  - 0.2737
  TRAIN_FILE: train.csv
  TRAIN_INTERVAL:
  - 1
  - 2
  TYPE_SAMPLERS: even_crop
  FRAME_SKIP: 16
  USE_GPU: true
  VAL_CLIP_LENGTH: ''
  VAL_CLIP_SIZE: ''
  VAL_FILE: val.csv
  VAL_INTERVAL:
  - 1
  VIDEO_PER: 0.3
  VIDEO_PER_TRAIN: 0.3
  VIDEO_PER_VAL: 0.3
  WORKERS: 8
HEAD:
  ATTN_DROPOUT: 0
  CROSS_DIM_HEAD: 64
  CROSS_HEADS: 1
  DEPTH: 3
  FF_DROPOUT: 0
  FINAL_CLASSIFIER_HEAD: true
  FOURIER_ENCODE_DATA: true
  INPUT_AXIS: 3
  INPUT_CHANNELS: 512
  LATENT_DIM: 512
  LATENT_DIM_HEAD: 64
  LATENT_HEADS: 8
  MAX_FREQ: 10.0
  NAME: perceiver
  NUM_CLASSES: 101
  NUM_FREQ_BANDS: 10
  NUM_LATENTS: 256
  SELF_PER_CROSS_ATTN: 1
  WEIGHT_TIE_LAYERS: true
TRAIN:
  BATCH_SIZE: 24
  DAMPENING: 0.0
  DEVICE: cuda:0
  EPOCH: 40
  GOOGLE_COLAB: false
  LEARNING_RATE: 0.1
  LOG_FILE_TRAIN: ''
  LOG_FILE_VAL: ''
  LOSS: crossentropylossmean
  LR_FACTOR: 0.1
  LR_MULT:
  - 1
  - 1
  - 1
  LR_STEP:
  - 10
  - 20
  - 30
  MODEL_NAME: ''
  MOMENTUM: 0.9
  NESTEROV: false
  OPTIMIZER: SGD
  PRETRAIN_CONFIG: ''
  PRETRAIN_PATH: ''
  RESULT_DIR: 'log'
  SAVE_FREQUENCY: 5
  TRAIN_CHECKPOINT: false
  WARM_UP: true
  WEIGHT_DECAY: 0.0001
  WORKERS: 8
